### ISSUE TITLE
Install script doesn't create new profile [Ubuntu GNOME]

### ISSUE THREAD

**Issue by BraydonS** [arcticicestudio/nord-gnome-terminal#16]
Hello! First off, love the theme, great work!

I'm having an issue installing it with the script. To start, Ive installed all the prerequisites listed in your requirements section successfully.

When I run the script it says:

> `[SUCCESS] Nord GNOME Terminal version 0.1.0 has been successfully applied to the newly created 'Nord' profile`

but no profile is visible in the the profile menu, nor in terminal/legacy/profiles in dconf-editor

**Comment by BraydonS** [comment]
Huh, Ive probably ran it about 15 times, but this last time it actually worked! Closing?

**Comment by arcticicestudio** [comment]
Nice to hear it works now :+1: 

Maybe this was related to a problem with the profile update notifier which might occur in some environments.
