### ISSUE TITLE
Add info about GIO modules variable to README

### ISSUE THREAD

**Issue by emilmelnikov** [arcticicestudio/nord-gnome-terminal#19]
I am using Ubuntu 16.04, and installation instructions from the README didn't work for me.
The script ran without errors, but the following message appeared:

```
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

The solution is described in [this StackOverflow answer](https://stackoverflow.com/a/45223897/2054455): before running the script, export the `GIO_EXTRA_MODULES` variable (it is OK to set it only for the current session).

```sh
export GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules
```

On a side note, add an installation one-liner to README:

```bash
curl -sL https://raw.githubusercontent.com/arcticicestudio/nord-gnome-terminal/develop/src/nord.sh | bash
```

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: and sorry for my late reply, currently busy with studying next to my job as dev. I'll take a look at it this weekend. Might be interesting to get to know the version this change has been introduced to GLib/GIO. 

Also looks like this will solve #20.
