### ISSUE TITLE
Have to unset $LS_COLORS

### ISSUE THREAD

**Issue by danstewart** [arcticicestudio/nord-gnome-terminal#22]
Hi,

I need to add `export LS_COLORS=""` to my `.bashrc` to allow the nord colors to apply when using `ls --color`.
I'm using Fedora 27.

Have I done something wrong or is this something that can be added to the install script?

Thanks

**Comment by arcticicestudio** [comment]
This sounds like a problem with your `LS_COLORS` setup **or** your're also affected by the problem reported in #19. Can you please test if it works when your're following the instructions posed in #19?

**Comment by danstewart** [comment]
I tried 
```
export GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules
./nord.sh
```

but no luck.

This also fixes the issue: `dircolors -p > ~/.dircolors`
From this [AskUbuntu question](https://askubuntu.com/questions/466198/how-do-i-change-the-color-for-.directories-with-ls-in-the-console).


Also found [this question on ask.fedoraproject](https://ask.fedoraproject.org/en/question/110157/ls_colors-env-value-differs-from-dircolors-output/).
Looks like Fedora uses `/etc/DIR_COLORS.256color`

**Comment by arcticicestudio** [comment]
Right now I don't know if we're talking about the same :smile: 
This theme only sets the colors that are available for the shell to use. It does **not** modify the colors for the `ls` command, that's the part of the [Nord dircolors](https://github.com/arcticicestudio/nord-dircolors) theme.

**Comment by danstewart** [comment]
I'm just dense and didn't realise they were separate things, thanks for the help :smile:
