### ISSUE TITLE
Same prompt as in the screenshot

### ISSUE THREAD

**Issue by Codem3ay** [arcticicestudio/nord-gnome-terminal#24]
How can I configure my bash prompt to get the same one as in the screenshot?! Can this be implemented in the installation .sh file?

**Comment by arcticicestudio** [comment]
Hi @Codem3ay :wave:
The prompt is not related to the color theme. The **project is only for your [terminal emulator][w-te]**, but **not the actual [shell][w-s] that runs inside it**.
The primary prompt (`$PS1`) can be customized through the `PROMPT_COMMAND` variable. For more details please take a look at the documentations of your shell (Bash, Zsh, Fish…) and this [extensive guide about shell customization][archw] in the great Arch Linux Wiki.

The prompt shown in the screenshot is my personal prompt and you can [find the source of it in my _.dotfile_ repository called „igloo“][igloo].

[w-te]: https://en.wikipedia.org/wiki/Terminal_emulator
[w-s]: https://en.wikipedia.org/wiki/Shell_(computing)
[archw]: https://wiki.archlinux.org/index.php/Bash/Prompt_customization
[igloo]: https://github.com/arcticicestudio/igloo/blob/6f483af31b755df31f6a625ab1796b8471bf1a9a/snowblocks/bash/core/prompt
