### ISSUE TITLE
Redundant logic in script

### ISSUE THREAD

**Issue by kgilmer** [arcticicestudio/nord-gnome-terminal#29]
I believe the following stanza is repeated twice, and the second one can be removed: https://github.com/arcticicestudio/nord-gnome-terminal/blob/develop/src/nord.sh#L76-L79

**Comment by arcticicestudio** [comment]
Hi @kgilmer :wave:, thanks for your contribution :+1:

This looks indeed like a hectic copy&paste mistake 😄 
Feel free to submit a PR to remove it, otherwise I'll resolve it when migrating the project to the new _Nord Docs_.
