### ISSUE TITLE
For Bash on Windows

### ISSUE THREAD

**Issue by harini9804** [arcticicestudio/nord-gnome-terminal#32]
I can't find a Preferences menu with the Bash on Windows, is there any way to add the Nord profiles to change the color scheme?

**Comment by arcticicestudio** [comment]
Hi @harini9804, I guess you're confusing something. [GNOME Terminal](https://wiki.gnome.org/Apps/Terminal) is a terminal for shells, like e.g. [Bash](<https://en.wikipedia.org/wiki/Bash_(Unix_shell)>) or [ZSH](https://en.wikipedia.org/wiki/Z_shell). You're referring to the (relative new) [Windows Terminal](https://github.com/microsoft/terminal) which is another terminal (see the [introduction blog post](https://devblogs.microsoft.com/commandline/windows-terminal-1-0/)). There is currently no official port project for _Windows Terminal_, but there's already a [open request](https://github.com/arcticicestudio/nord/issues/123) including multiple ports made by other users.

Therefore I'll close this issue. Please subscribe to the linked issue for progress updates.
