### ISSUE TITLE
[QUESTION] Terminal theme

### ISSUE THREAD

**Issue by ghost** [arcticicestudio/nord-gnome-terminal#36]
Just a quick question, do you use zsh in this picture? If so, what is the theme and how can I get it/install it.
https://raw.githubusercontent.com/arcticicestudio/nord-gnome-terminal/develop/assets/scrot-colortest.png
Sorry for bothering

**Comment by arcticicestudio** [comment]
Hi @trashCODEeR :wave:

I guess you're referring to the [shell prompt][1] when you say "theme". If so then you can find [my own custom ZSH shell promt theme in my _.dotfile_ repository][2]. If you refer to the `colortest` then this was a script that from the [stark/Color-Scripts][3] repository.

[1]: https://en.wikibooks.org/wiki/Guide_to_Unix/Explanations/Shell_Prompt
[2]: https://github.com/arcticicestudio/igloo/tree/414a7df82fd675/snowblocks/zsh#prompt-theme
[3]: https://github.com/stark/Color-Scripts

**Comment by ghost** [comment]
Oh ok. Thanks! I use oh-my-zsh with zsh, so I just added the igloo.zsh as igloo.zsh-theme and it works! Thanks once again
