### ISSUE TITLE
[QUESTION] colortest

### ISSUE THREAD

**Issue by mikafouenski** [arcticicestudio/nord-gnome-terminal#4]
This screenshot is realy nice. What is your script for colortest ? :)

**Comment by arcticicestudio** [comment]
Nice to see you like it 😄 
You can check out my dotfile repository called [igloo](https://github.com/arcticicestudio/igloo). My [`colors`](https://github.com/arcticicestudio/igloo/blob/develop/snowblocks/bash/bin/colors) script is located in the `bash` *snowblock*.
