### ISSUE TITLE
question: what is your terminal setup?

### ISSUE THREAD

**Issue by zer09** [arcticicestudio/nord-gnome-terminal#5]
Hello good day,

Just want to ask, how did you setup your terminal, are you using powerline?
It looks to unique. it just simple, clean, but beautiful.

Thanks.

**Comment by arcticicestudio** [comment]
Sorry for my late response, have been busy with my job.
I've created it on my own, you can check out the [prompt](https://github.com/arcticicestudio/igloo/blob/develop/snowblocks/bash/core/prompt) file in my dotfile repository.

**Comment by zer09** [comment]
That's ok, no problem, I just saw the bash-it and I thought it was it, so I just closed this.

Thanks.
