### ISSUE TITLE
Clobbered my default profile

### ISSUE THREAD

**Issue by RhysU** [arcticicestudio/nord-gnome-terminal#6]
Running `nord.sh` clobbered my 'Default' profile.  The script should install alongside any existing profile.

**Comment by arcticicestudio** [comment]
Which OS- and GNOME Terminal version are you running?
The script works fine, it clones the default profile and leaves everything untouched, but it may be related to #3 which may be related to a distribution dependency problem.

**Comment by RhysU** [comment]
Gnome Terminal 3.20.2 on Ubuntu 17.04.

**Comment by arcticicestudio** [comment]
I've set up a Ubuntu 17.04 VirtualBox maschine and tried to reproduce it, but everything works fine. The script runs without any errors and creates a **copy** of the `default` profile.
have you installed the `dconf-tools` package? (`sudo apt-get install dconf-tools`)
It is not installed by default and maybe the dconf falls back to the outdated `gconftool` instead.

**Comment by RhysU** [comment]
Apologies for the excessively slow replies here.  I had not installed the `dconf-tools` package.  Closing.

**Comment by arcticicestudio** [comment]
Nice to hear it works for you now. I'll add a note to the documentation that the `dconf-tools` package must be installed before running the script :smile:

**Comment by arcticicestudio** [comment]
Related to #3.
