### ISSUE TITLE
[Question] Theme on the screenshot

### ISSUE THREAD

**Issue by yqbk** [arcticicestudio/nord-gnome-terminal#7]
Could you please tell me what is the theme that you are using?

I mean this screenshot: 
![this screenshot:](https://raw.githubusercontent.com/arcticicestudio/nord-gnome-terminal/develop/src/assets/scrot-readme-default-profile.png "screenshot")

**Comment by arcticicestudio** [comment]
The awesome GTK theme [Arc](https://github.com/horst3180/arc-theme).
